# -*- coding: utf-8 -*-
"""Tema 12python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CXkCKkd5V7PbLu6HsYhhV-nVItAksWuG
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

img_bgr = cv2.imread('starry_night.jpg')
img = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB).astype(np.float32) / 255.0

# 1. Gamma
gamma = 2.2
img_no_gamma = np.power(img, gamma)

# 2. HDR vs LDR
hdr_raw = img * 3.0
ldr_clipped = np.clip(hdr_raw, 0, 1)
hdr_tonemapped = hdr_raw / (1 + hdr_raw)

# 3. Aliasing vs Antialiasing (FORZADO)
# Reducimos a un tamaño muy pequeño para crear "escalones"
h, w = img.shape[:2]
factor = 16 # Reducción agresiva
small_size = (w // factor, h // factor)

# Aliasing: Usamos NEAREST (salta píxeles, crea serrucho)
low_res_aliased = cv2.resize(img, small_size, interpolation=cv2.INTER_NEAREST)
aliased = cv2.resize(low_res_aliased, (w, h), interpolation=cv2.INTER_NEAREST)

# Antialiasing: Usamos AREA (promedia píxeles para suavizar antes de reducir)
low_res_aa = cv2.resize(img, small_size, interpolation=cv2.INTER_AREA)
antialiased = cv2.resize(low_res_aa, (w, h), interpolation=cv2.INTER_LINEAR)

# Visualización
fig, axs = plt.subplots(2, 3, figsize=(15, 10))
axs[0,0].imshow(img); axs[0,0].set_title('Normal'); axs[0,0].axis('off')
axs[0,1].imshow(img_no_gamma); axs[0,1].set_title('Sin Gamma (Lineal)'); axs[0,1].axis('off')
axs[0,2].imshow(ldr_clipped); axs[0,2].set_title('LDR (Recortado)'); axs[0,2].axis('off')
axs[1,0].imshow(hdr_tonemapped); axs[1,0].set_title('HDR (Tone Mapping)'); axs[1,0].axis('off')

# IMPORTANTE: interpolation='none' en imshow para que no suavice el aliasing al mostrarlo
axs[1,1].imshow(aliased, interpolation='none'); axs[1,1].set_title('Con Aliasing (Pixeleado)'); axs[1,1].axis('off')
axs[1,2].imshow(antialiased, interpolation='none'); axs[1,2].set_title('Con Antialiasing (Suavizado)'); axs[1,2].axis('off')

plt.tight_layout()
plt.show()